//
//  NoteViewController.swift
//  EasyList
//
//  Created by Aristeidis Panagiotopoulos on 23/10/2018.
//  Copyright (c) 2018 arisPanagiotopoulos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoteDisplayLogic: class
{
  func displaySomething(viewModel: Note.Something.ViewModel)
}

class NoteViewController: UIViewController, NoteDisplayLogic
{
  var interactor: NoteBusinessLogic?
  var router: (NSObjectProtocol & NoteRoutingLogic & NoteDataPassing)?

  // MARK: Object lifecycle
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = NoteInteractor()
    let presenter = NotePresenter()
    let router = NoteRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Note.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Note.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
