//
//  NoteWorker.swift
//  EasyList
//
//  Created by Aristeidis Panagiotopoulos on 23/10/2018.
//  Copyright (c) 2018 arisPanagiotopoulos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

protocol NoteRepositoryLogic {
    func createNote(title: String, text: String)
}

class NoteWorker: AbstractRepository, NoteRepositoryLogic
{
    
    func createNote(title: String = "", text: String = "") {
        let note = NoteModel(title: title)
        note.title = title
        note.text = text
        save(entity: note)
    }
    
    func getAll() -> Results<NoteModel> {
        return realm.objects(NoteModel.self)
    }
}
