//
//  NotePresenter.swift
//  EasyList
//
//  Created by Aristeidis Panagiotopoulos on 23/10/2018.
//  Copyright (c) 2018 arisPanagiotopoulos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotePresentationLogic
{
  func presentSomething(response: Note.Something.Response)
}

class NotePresenter: NotePresentationLogic
{
  weak var viewController: NoteDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Note.Something.Response)
  {
    let viewModel = Note.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
