//
//  NoteInteractor.swift
//  EasyList
//
//  Created by Aristeidis Panagiotopoulos on 23/10/2018.
//  Copyright (c) 2018 arisPanagiotopoulos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoteBusinessLogic
{
  func doSomething(request: Note.Something.Request)
}

protocol NoteDataStore
{
  //var name: String { get set }
}

class NoteInteractor: NoteBusinessLogic, NoteDataStore
{
  var presenter: NotePresentationLogic?
  var worker: NoteWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Note.Something.Request)
  {
    worker = NoteWorker()
    worker?.doSomeWork()
    
    let response = Note.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
