//
//  NoteWorker.swift
//  EasyList
//
//  Created by Aristeidis Panagiotopoulos on 23/10/2018.
//  Copyright (c) 2018 arisPanagiotopoulos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

class NoteWorker
{
    func doSomeWork()
    {
    }
    
    func createNote(title: String = "")
    {
        let realm = try! Realm()

        try! realm.write {
            let note = NoteModel()
            note.title = title
            realm.add(note)
        }
    }
}
