//
//  NotePresenterTests.swift
//  EasyList
//
//  Created by Aristeidis Panagiotopoulos on 23/10/2018.
//  Copyright (c) 2018 arisPanagiotopoulos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import EasyList
import XCTest

class NotePresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: NotePresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupNotePresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupNotePresenter()
  {
    sut = NotePresenter()
  }
  
  // MARK: Test doubles
  
  class NoteDisplayLogicSpy: NoteDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: Note.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = NoteDisplayLogicSpy()
    sut.viewController = spy
    let response = Note.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
