//
//  NoteWorkerTests.swift
//  EasyList
//
//  Created by Aristeidis Panagiotopoulos on 23/10/2018.
//  Copyright (c) 2018 arisPanagiotopoulos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import EasyList
import XCTest
import RealmSwift

class NoteWorkerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: NoteWorker = NoteWorker()
    var realm = try! Realm()
    
    
    // MARK: Test lifecycle
    
    override func tearDown()
    {
        try! realm.write {
            realm.deleteAll()
        }
        super.tearDown()
        
    }
    
    
    // MARK: Tests
    
    func test_NoteWorker_Should_Create_Note()
    {
        // Given
        //
        
        // When
        sut.createNote(title: "hello")
        
        // Then
        try! realm.write {
            let queryResult = realm.objects(NoteModel.self)
            XCTAssertEqual(1, queryResult.count, "1 Note Should Exist")
            let note = queryResult[0]
            XCTAssertEqual(note.title, "hello")
        }
    }
}
