//
//  NoteInteractorTests.swift
//  EasyList
//
//  Created by Aristeidis Panagiotopoulos on 23/10/2018.
//  Copyright (c) 2018 arisPanagiotopoulos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import EasyList
import XCTest

class NoteInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: NoteInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupNoteInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupNoteInteractor()
  {
    sut = NoteInteractor()
  }
  
  // MARK: Test doubles
  
  class NotePresentationLogicSpy: NotePresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: Note.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = NotePresentationLogicSpy()
    sut.presenter = spy
    let request = Note.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
